import type { Content, Comment } from '@/lib/definitions';

export const mockContent: Content[] = [
  {
    id: '1',
    title: 'Cosmic Odyssey',
    description:
      'A thrilling space adventure that takes you to the edge of the galaxy. A team of explorers discovers a secret that could change humanity forever.',
    posterPath: 'https://picsum.photos/seed/poster-1/500/750',
    backdropPath: 'https://picsum.photos/seed/hero-backdrop/1280/720',
    genres: ['Sci-Fi', 'Adventure', 'Action'],
    releaseDate: '2024-05-15',
    rating: 8.5,
    type: 'movie',
    trailerUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
  },
  {
    id: '2',
    title: 'The Last Kingdom',
    description:
      'In a land torn by war, a young hero rises to unite the factions and bring peace. A historical epic of bravery and sacrifice.',
    posterPath: 'https://picsum.photos/seed/poster-2/500/750',
    backdropPath: 'https://picsum.photos/seed/backdrop-2/1280/720',
    genres: ['Action', 'Drama', 'History'],
    releaseDate: '2024-03-20',
    rating: 9.1,
    type: 'tv',
    trailerUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
  },
  {
    id: '3',
    title: 'Cyber City Blues',
    description:
      'In a neon-drenched metropolis of the future, a cynical detective hunts for a mysterious hacker. A neo-noir thriller.',
    posterPath: 'https://picsum.photos/seed/poster-3/500/750',
    backdropPath: 'https://picsum.photos/seed/backdrop-3/1280/720',
    genres: ['Thriller', 'Sci-Fi', 'Mystery'],
    releaseDate: '2024-04-01',
    rating: 8.2,
    type: 'movie',
    trailerUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
  },
  {
    id: '4',
    title: 'Echoes of the Past',
    description: 'A young woman discovers she can communicate with ghosts, and must solve a century-old mystery to save her town.',
    posterPath: 'https://picsum.photos/seed/poster-4/500/750',
    backdropPath: 'https://picsum.photos/seed/backdrop-4/1280/720',
    genres: ['Fantasy', 'Drama', 'Mystery'],
    releaseDate: '2024-02-10',
    rating: 7.8,
    type: 'tv',
  },
  {
    id: '5',
    title: 'The Great Heist',
    description: 'A team of charismatic thieves plans the ultimate robbery. But with betrayal at every turn, can they pull it off?',
    posterPath: 'https://picsum.photos/seed/poster-5/500/750',
    backdropPath: 'https://picsum.photos/seed/backdrop-5/1280/720',
    genres: ['Crime', 'Thriller', 'Action'],
    releaseDate: '2024-06-01',
    rating: 8.8,
    type: 'movie',
  },
  {
    id: '6',
    title: 'Love in the City',
    description: 'A romantic comedy about two strangers who meet in a bustling city and find love in the most unexpected places.',
    posterPath: 'https://picsum.photos/seed/poster-6/500/750',
    backdropPath: 'https://picsum.photos/seed/backdrop-6/1280/720',
    genres: ['Romance', 'Comedy'],
    releaseDate: '2024-01-25',
    rating: 7.5,
    type: 'tv',
  },
  {
    id: '7',
    title: 'Mountain of Fear',
    description: 'A group of climbers gets trapped on a remote peak and must fight for survival against the elements and a hidden predator.',
    posterPath: 'https://picsum.photos/seed/poster-7/500/750',
    backdropPath: 'https://picsum.photos/seed/backdrop-7/1280/720',
    genres: ['Horror', 'Thriller'],
    releaseDate: '2023-10-31',
    rating: 6.9,
    type: 'movie',
  },
  {
    id: '8',
    title: 'Kings of the Court',
    description: 'A documentary following the rise of a legendary basketball team and its iconic star player.',
    posterPath: 'https://picsum.photos/seed/poster-8/500/750',
    backdropPath: 'https://picsum.photos/seed/backdrop-8/1280/720',
    genres: ['Documentary', 'Sport'],
    releaseDate: '2024-05-22',
    rating: 9.0,
    type: 'tv',
  },
  {
    id: '9',
    title: 'The Alchemist\'s Secret',
    description: 'An animated adventure about a young apprentice who must find a mythical artifact to save her master.',
    posterPath: 'https://picsum.photos/seed/poster-9/500/750',
    backdropPath: 'https://picsum.photos/seed/backdrop-9/1280/720',
    genres: ['Animation', 'Adventure', 'Family'],
    releaseDate: '2024-06-12',
    rating: 8.1,
    type: 'movie',
  },
  {
    id: '10',
    title: 'Galactic Chronicles',
    description: 'A sprawling space opera series following the intertwined destinies of various characters across a vast galaxy.',
    posterPath: 'https://picsum.photos/seed/poster-10/500/750',
    backdropPath: 'https://picsum.photos/seed/backdrop-10/1280/720',
    genres: ['Sci-Fi', 'Drama'],
    releaseDate: '2024-07-01',
    rating: 8.7,
    type: 'tv',
  },
  {
    id: '11',
    title: 'Midnight Shadow',
    description: 'A gritty crime drama about an undercover cop who infiltrates a dangerous syndicate.',
    posterPath: 'https://picsum.photos/seed/poster-11/500/750',
    backdropPath: 'https://picsum.photos/seed/backdrop-11/1280/720',
    genres: ['Crime', 'Drama', 'Thriller'],
    releaseDate: '2023-11-15',
    rating: 8.4,
    type: 'movie',
  },
  {
    id: '12',
    title: 'Jesters & Jokers',
    description: 'A hilarious sitcom about a group of friends who run a failing comedy club.',
    posterPath: 'https://picsum.photos/seed/poster-12/500/750',
    backdropPath: 'https://picsum.photos/seed/backdrop-12/1280/720',
    genres: ['Comedy'],
    releaseDate: '2024-04-18',
    rating: 7.9,
    type: 'tv',
  },
];


export const mockComments: Comment[] = [
    {
        id: 'c1',
        author: 'CinephileChris',
        authorId: 'user1',
        avatarUrl: 'https://picsum.photos/seed/avatar1/200/200',
        text: 'This movie was absolutely breathtaking! The cinematography was stunning.',
        timestamp: 1672531200000,
        replies: [
            {
                id: 'c1_r1',
                author: 'MovieMaven',
                authorId: 'user2',
                avatarUrl: 'https://picsum.photos/seed/avatar2/200/200',
                text: 'I agree! I was on the edge of my seat the entire time.',
                timestamp: 1672534800000,
                replies: []
            }
        ]
    },
    {
        id: 'c2',
        author: 'TVJunkieJane',
        authorId: 'user3',
        avatarUrl: 'https://picsum.photos/seed/avatar3/200/200',
        text: 'I couldn\'t get into it. The pacing felt really slow in the beginning.',
        timestamp: 1672617600000,
        replies: []
    }
];
